/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Filter { 
    title?: any;
    description?: any;
    category?: any;
    from?: any;
    to?: any;
    organizer?: any;
    structure?: any;
}