/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { StructureImage } from './structureImage';

export interface Structure { 
    createdBy?: any;
    creationDate?: any;
    lastModifiedBy?: any;
    lastModifiedDate?: any;
    id?: any;
    name?: any;
    address?: Address;
    country: any;
    structureImage?: StructureImage;
    structureSectors?: any;
}