/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Sector } from './sector';
import { Structure } from './structure';

export interface StructureSector { 
    id?: any;
    structure?: Structure;
    sector?: Sector;
    capacity?: any;
}