/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WishlistDTO { 
    id: any;
    name: any;
    creationDate: any;
    scope: any;
    creator: any;
    wishedEvents?: any;
    sharedUsers?: any;
}